### PR TITLE
Make sure pointer is not changed between messages

### PR DESCRIPTION
**Pull request by halkeye**
https://github.com/dominikh/go-tools/issues/163 and Essentially https://github.com/andreas/go-bayeux-client/issues/1#issuecomment-422268214

### CODE REVIEW

**Comment by irzhywau** [comment]
Thank you @halkeye for this PR
I saw the change but still Im not yet sure about it. I will take a further look anyway.

**Comment by halkeye** [comment]
If you have any ability to contact the upstream author you should bug them about adding a license, since no license means nobody can use it.

Re the fix, I'm not sure why others didn't run into it, but I was always getting the wrong message for the first one. Maybe it's just salesforce being wierd

**Comment by andreas** [comment]
Maybe it's worth adding a test case which demonstrates the issue and the fix? 🙂

**Comment by halkeye** [comment]
It seems a little unfair to ask someone contributing a one liner fix to try and setup testing for a library, especially one with Concurrency

My coworker setup a go playground link to demonstrate the problem. I can share that link. It demonstrates the issue with pointers and range, not this specific issue. (Essentially a printf of the address inside the loop)

My guess is that salesforce returns multiple messages in the reply which is why this gets triggered since msg is a pointer to the message not the message itself.

**Comment by andreas** [comment]
I don't think it's unfair to ask, but it's totally fine to say it's too much effort (which I guess is what you're saying) 🙂

**Comment by halkeye** [comment]
https://go.dev/play/p/3SpYND5j1eF is the playground link

> I don't think it's unfair to ask, but it's totally fine to say it's too much effort (which I guess is what you're saying) 🙂

i guess thats true. I would totally be up for adding a test case, but getting an initial one done is pretty hard. I would think send() should be refactored and split into two functions (one http, one processing) so its easier to test. But since http client is able to be passed into new, it should be somewhat testable but a decent amount of work.

I could use the excuse to up my go testing abilities, we will see

I did test the upstream library after the fix and license was applied and things work for me now.

**Comment by halkeye** [comment]
I'm going to close this. We ended up doing a custom solution, one that just had one channel, and called connect each time http returned.

**Pull request closed without merging**
